
spring:
 application:
    name: spaceship
 h2:
   console:
    enabled: true
    path: /h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
 jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    default_schema: app
    show-sql: true
 hibernate:
    ddl-auto: validate
 flyway:
  enabled: true
  